### ISSUE TITLE
[Android - Bug] Gradle version doesn't support OPACITY

### ISSUE THREAD

**Issue by camaron-izeni** [facebookincubator/Keyframes#109]
The version of Keyframes imported from Gradle doesn't include support for the OPACITY constant as well as some other features (namely pausing and resuming an animation). When I import keyframes directly (either via jar or by cloning the repository) the issue goes away (as well as the other issues I mentioned.) I would appreciate if someone would release a new gradle build.

Here is the stacktrace of the error in question:

```
FATAL EXCEPTION: main
        Process: com.owletcare.owletfield, PID: 11365
        java.lang.IllegalArgumentException: OPACITY is not a constant in com.facebook.keyframes.model.KFAnimation$PropertyType
            at java.lang.Enum.valueOf(Enum.java:198)
            at com.facebook.keyframes.model.KFAnimation$PropertyType.valueOf(KFAnimation.java:41)
            at com.facebook.keyframes.deserializers.KFAnimationDeserializer.readObject(KFAnimationDeserializer.java:40)
            at com.facebook.keyframes.deserializers.KFAnimationDeserializer$1.readObjectImpl(KFAnimationDeserializer.java:29)
            at com.facebook.keyframes.deserializers.KFAnimationDeserializer$1.readObjectImpl(KFAnimationDeserializer.java:26)
            at com.facebook.keyframes.deserializers.AbstractListDeserializer.readList(AbstractListDeserializer.java:35)
            at com.facebook.keyframes.deserializers.KFFeatureDeserializer.readObject(KFFeatureDeserializer.java:71)
            at com.facebook.keyframes.deserializers.KFFeatureDeserializer$1.readObjectImpl(KFFeatureDeserializer.java:32)
            at com.facebook.keyframes.deserializers.KFFeatureDeserializer$1.readObjectImpl(KFFeatureDeserializer.java:29)
            at com.facebook.keyframes.deserializers.AbstractListDeserializer.readList(AbstractListDeserializer.java:35)
            at com.facebook.keyframes.deserializers.KFImageDeserializer.readObject(KFImageDeserializer.java:52)
            at com.facebook.keyframes.deserializers.KFImageDeserializer.deserialize(KFImageDeserializer.java:35)
            at com.owletcare.owlet.controls.KeyframesView.loadAsset(KeyframesView.java:66)
            at com.owletcare.owlet.controls.KeyframesView.loadAsset(KeyframesView.java:59)
            at com.owletcare.owlet.fragments.TestKeyframesFragment.onViewCreated(TestKeyframesFragment.java:33)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1132)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by LazyChild** [comment]
Should be resolved in v1.1.0 release
