### ISSUE TITLE
Animating Opacity

### ISSUE THREAD

**Issue by androidDev0037436** [facebookincubator/Keyframes#43]
Hello.

I was just wondering if animating opacity is supported or will be soon. I get this exception when I try to deserialize my json on android. 
     
     Caused by: java.lang.IllegalArgumentException: No enum constant com.facebook.keyframes.model.KFAnimation.PropertyType.OPACITY
        at java.lang.Enum.valueOf(Enum.java:254)
        at com.facebook.keyframes.model.KFAnimation$PropertyType.valueOf(KFAnimation.java:41)
        at com.facebook.keyframes.deserializers.KFAnimationDeserializer.readObject(KFAnimationDeserializer.java:40)

...

**Comment by lozzle** [comment]
Hey @androidDev0037436!  We don't have it in the main branch, but if you want to check out this branch: https://github.com/facebookincubator/Keyframes/tree/new-android-features

This includes animating opacity on Android, as well as anchor point and some basic masking functionality.

**Comment by androidDev0037436** [comment]
Thank you so much @lozzle! It works really well.

Awesome library by the way!!!
