### ISSUE TITLE
keyframes-cli syntax error

### ISSUE THREAD

**Issue by fandy** [facebookincubator/Keyframes#82]
I'm getting a syntax error when running `$ keyframes-cli` with a comp saved and open:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/fang/.nvm/versions/node/v5.7.0/lib/node_modules/keyframes-cli/keyframes-cli.js:13:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Using After Effects CC 2017 on Sierra and I have followed the README for installing `keyframes-cli`.

**Comment by LazyChild** [comment]
node version?

**Comment by fandy** [comment]
That fixes it, thanks!
